### ISSUE TITLE
Crash on Startup with hcbrewing enabled

### ISSUE THREAD

**Issue by fullskele** [Rebirth-of-the-Night/BetterWithMods#3]
Hello, after transferring from BWM + BWA to BetterWithEverything, I encountered a crash on startup, which persisted until the hcbrewing config from BWM was disabled. See below:

https://gist.github.com/fullskele/d5b1d89a23ecd13a4cfdf09e6dcf434c

**Comment by Biviho** [comment]
hi! similar issue here: crash on startup with this error after changing bwm+bwa to bwe, fixed after disabling hcbrewing, i think it might be caused by some weird interaction with some other mod during startup, i'll do a deeper check to find the culprit (it will take time, 424 mods in my pack)

[the mighty log](https://mclo.gs/a3j8atH)
